# Site settings
title: 码路
email: zqzhao5@gmail.com
description: "Really cool blog about ... something"
baseurl: "/blog"
url: "http://martian101.github.io"
twitter_username: zqzhao5
github_username: Martian101
disqus_username: false
isso_domain: comments.martian101.github.io/blog

# Build settings
markdown: redcarpet
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
